version: "3"

services:
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
    ports:
      - 5432:5432

  log-database:
    image: mongo
    ports:
      - 27017:27017
