name: Build Application image

on:
  push:
    branches:
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Chekout git files
      uses: actions/checkout@v3
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/temvagamestreapi:${{github.sha}}}},${{secrets.DOCKERHUB_USERNAME}}/temvagamestreapi:latest
