name: Run Lint

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  lint: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git files
        uses: actions/checkout@v3
        
      - name: Use Node.js Version 20.X
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

